### ISSUE TITLE
ansible-lint crashes when encountering the '\t' character

### ISSUE THREAD

**Issue by jody-frankowski** [ansible/ansible-lint#166]
# Issue Type
- Bug report
# Ansible and Ansible Lint details

```
ansible 2.0.1.0
ansible-lint 2.3.9
```
- ansible installation method: archlinux package
- ansible-lint installation method: pip
# Desired Behaviour

ansible-lint does not crash.
# Actual Behaviour
- Playbook:

```
    # /!\ Do not remove the tab in the line='...' field (OpenBSD syslogd only
    # cares about tabs)
    - name: Configure syslog to send logs to the audit server
      lineinfile: dest=/etc/syslog.conf regexp='.*10.0.0.18.*' line='*.*      @10.0.0.18'
```
- Output of `ansible-playbook --syntax-check playbook`:

```
ansible-playbook --syntax-check playbooks/groups/test/syslog.yml                                                                                                                                            
playbook: playbooks/groups/test/syslog.yml
```
- Output of running ansible-lint:

```
Traceback (most recent call last):
  File "/home/me/.local/bin/ansible-lint", line 116, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/me/.local/bin/ansible-lint", line 103, in main
    matches = runner.run()
  File "/home/me/.local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 211, in run
    skip_list=set(self.skip_list)))
  File "/home/me/.local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 123, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/home/me/.local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 57, in matchtasks
    yaml = ansiblelint.utils.parse_yaml_linenumbers(text)
  File "/home/me/.local/lib/python2.7/site-packages/ansiblelint/utils.py", line 320, in parse_yaml_linenumbers
    data = loader.get_single_data()
  File "/usr/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/me/.local/lib/python2.7/site-packages/ansiblelint/utils.py", line 309, in compose_node
    node = Composer.compose_node(loader, parent, index)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/home/me/.local/lib/python2.7/site-packages/ansiblelint/utils.py", line 309, in compose_node
    node = Composer.compose_node(loader, parent, index)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/me/.local/lib/python2.7/site-packages/ansiblelint/utils.py", line 309, in compose_node
    node = Composer.compose_node(loader, parent, index)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/home/me/.local/lib/python2.7/site-packages/ansiblelint/utils.py", line 309, in compose_node
    node = Composer.compose_node(loader, parent, index)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python2.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<string>", line 9, column 75:
     ... gexp='.*10.0.0.18.*' line='*.*       @10.0.0.18'
```

**Comment by willthames** [comment]
I've had a good look at this, and it's frustrating that ansible parses it fine but ansible-lint doesn't. I can't see how ansible is managing it. I can't use ansible's parsing in this case because ansible-lint's parsing adds line numbers to the parsed result which is helpful for outputting line number info (it might be possible to reuse some of Ansible's parsing, but doing that and retaining compatibility with Ansible 1.9, and retaining line numbers goes well beyond how much time I have to look at this!)

The easy workaround is to replace the literal tab character with `\t`. This seems to work with my tests.
