### ISSUE TITLE
Unhandled exception when trying to lint an included task file with invalid syntax

### ISSUE THREAD

**Issue by jack1142** [ansible/ansible-lint#1815]
##### Summary
Running `ansible-lint` on a playbook that includes (through `include_tasks:`) a file with tasks that uses invalid syntax results in an unhandled exception error.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details
```console (paste below)
$ ansible --version
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/ans/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ubuntu/ans/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True

$ ansible-lint --version
ansible-lint 5.3.2 using ansible 2.12.1
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT
Ubuntu 20.04 LTS

##### STEPS TO REPRODUCE

1. Make an `example_playbook.yaml` file:
```yaml
- hosts: localhost
  connection: local
  tasks:
    - include_tasks: tasks/task1.yaml
```
2. Make a `tasks/task1.yaml` file:
```yaml
- name: Test task.
  block:
    ansible.builtin.debug:
      msg: Test task!
```
3. Run `ansible-lint`.
4. See error.

##### Desired Behaviour
I expected `ansible-lint` to show a meaningful syntax error.

##### Actual Behaviour
I got an unhandled exception:
```console
$ ansible-lint
Traceback (most recent call last):
  File "/home/ubuntu/ans/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/home/ubuntu/ans/lib/python3.8/site-packages/ansiblelint/__main__.py", line 310, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/home/ubuntu/ans/lib/python3.8/site-packages/ansiblelint/__main__.py", line 239, in main
    result = _get_matches(rules, options)
  File "/home/ubuntu/ans/lib/python3.8/site-packages/ansiblelint/runner.py", line 201, in _get_matches
    matches.extend(runner.run())
  File "/home/ubuntu/ans/lib/python3.8/site-packages/ansiblelint/runner.py", line 136, in run
    matches.extend(self._emit_matches(files))
  File "/home/ubuntu/ans/lib/python3.8/site-packages/ansiblelint/runner.py", line 169, in _emit_matches
    for child in ansiblelint.utils.find_children(lintable):
  File "/home/ubuntu/ans/lib/python3.8/site-packages/ansiblelint/utils.py", line 255, in find_children
    for child in play_children(basedir, item, lintable.kind, playbook_dir):
  File "/home/ubuntu/ans/lib/python3.8/site-packages/ansiblelint/utils.py", line 328, in play_children
    return delegate_map[k](basedir, k, v, parent_type)
  File "/home/ubuntu/ans/lib/python3.8/site-packages/ansiblelint/utils.py", line 364, in _taskshandlers_children
    children = _get_task_handler_children_for_tasks_or_playbooks(
  File "/home/ubuntu/ans/lib/python3.8/site-packages/ansiblelint/utils.py", line 425, in _get_task_handler_children_for_tasks_or_playbooks
    path_dwim(basedir, task_handler[task_handler_key]), kind=child_type
TypeError: string indices must be integers
```

Here's the output of `ansible-playbook --syntax-check` on both of the files:
```console
$ ansible-playbook --syntax-check example_playbook.yaml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

playbook: example_playbook.yaml


$ ansible-playbook --syntax-check tasks/test_task.yaml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'
ERROR! 'block' is not a valid attribute for a Play

The error appears to be in '/home/ubuntu/ans-test-lint/tasks/test_task.yaml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Test task.
  ^ here
```

As expected, there's a syntax error for `tasks/test_task.yaml`. However, I would expect `ansible-lint` to show a friendly error message, same as it does when there's an issue directly in the playbook.

**Comment by relrod** [comment]
We'd accept a patch to fix this exception.

**Comment by ssbarnea** [comment]
AFAIK, this was fixed in current versions.

**Comment by Lusitaniae** [comment]
Would a backport to v5.x be possible?
