### ISSUE TITLE
rich.errors.MarkupError when task name has slashes in square brackets

### ISSUE THREAD

**Issue by kostyaplis** [ansible/ansible-lint#2507]
##### Summary
Affected formatter: `rich`
A task name including `[/]` will cause a fatal error in case of rule match.

##### Ansible and Ansible Lint details

```console 
$ ansible-lint --version
ansible-lint 6.7.0 using ansible 2.13.3
```
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

Test playbook:
```
- name: Test
  hosts: localhost
  tasks:
    - name: create test folder [/tmp/test]
      ansible.builtin.file:
        path: /tmp/test
        state: directory
        mode: 0750
```

```console
$ ansible-lint playbook-test.yml

WARNING  Listing 1 violation(s) that are fatal
Traceback (most recent call last):
  File "/Users/konstantinplis/.pyenv/versions/3.10.1/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/Users/konstantinplis/.pyenv/versions/3.10.1/lib/python3.10/site-packages/ansiblelint/__main__.py", line 307, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/Users/konstantinplis/.pyenv/versions/3.10.1/lib/python3.10/site-packages/ansiblelint/__main__.py", line 247, in main
    app.render_matches(result.matches)
  File "/Users/konstantinplis/.pyenv/versions/3.10.1/lib/python3.10/site-packages/ansiblelint/app.py", line 94, in render_matches
    console.print(self.formatter.format(match), highlight=False)
  File "/Users/konstantinplis/.pyenv/versions/3.10.1/lib/python3.10/site-packages/rich/console.py", line 1647, in print
    renderables = self._collect_renderables(
  File "/Users/konstantinplis/.pyenv/versions/3.10.1/lib/python3.10/site-packages/rich/console.py", line 1511, in _collect_renderables
    self.render_str(
  File "/Users/konstantinplis/.pyenv/versions/3.10.1/lib/python3.10/site-packages/rich/console.py", line 1403, in render_str
    rich_text = render_markup(
  File "/Users/konstantinplis/.pyenv/versions/3.10.1/lib/python3.10/site-packages/rich/markup.py", line 161, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/tmp/test]' at position 265 doesn't match any open tag
```

##### Desired Behavior

No fatal error

##### Actual Behavior

Fatal error thrown

**Comment by ssbarnea** [comment]
I will release a hotfix for it today, I know why is happening and we already have few other fixes merged.
