### ISSUE TITLE
Internal bug: rich.errors.MarkupError: closing tag '[/]' at position 0 has nothing to close

### ISSUE THREAD

**Issue by nvuillam** [ansible/ansible-lint#2571]
##### Summary

Since latest version of ansible-lint, there is an internal crash within [MegaLinter](https://oxsecurity.github.io/megalinter/latest/descriptors/ansible_ansible_lint/)

```shell
INFO     Set ANSIBLE_LIBRARY=/root/.cache/ansible-compat/770e60/modules:/root/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/root/.cache/ansible-compat/770e60/collections:/root/.ansible/collections:/usr/share/ansible/collections
INFO     Set ANSIBLE_ROLES_PATH=/root/.cache/ansible-compat/770e60/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
INFO     Set ANSIBLE_LIBRARY=/root/.cache/ansible-compat/770e60/modules:/root/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/root/.cache/ansible-compat/770e60/collections:/root/.ansible/collections:/usr/share/ansible/collections
INFO     Set ANSIBLE_ROLES_PATH=/root/.cache/ansible-compat/770e60/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
INFO     Discovered files to lint using: git ls-files --cached --others --exclude-standard -z
INFO     Excluded removed files using: git ls-files --deleted -z
WARNING  Listing 13 violation(s) that are fatal
Traceback (most recent call last):
  File "/venvs/ansible-lint/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/venvs/ansible-lint/lib/python3.10/site-packages/ansiblelint/__main__.py", line 310, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/venvs/ansible-lint/lib/python3.10/site-packages/ansiblelint/__main__.py", line 250, in main
    app.render_matches(result.matches)
  File "/venvs/ansible-lint/lib/python3.10/site-packages/ansiblelint/app.py", line 82, in render_matches
    console.print(self.formatter.format(match), highlight=False)
  File "/venvs/ansible-lint/lib/python3.10/site-packages/rich/console.py", line 1668, in print
    renderables = self._collect_renderables(
  File "/venvs/ansible-lint/lib/python3.10/site-packages/rich/console.py", line 1532, in _collect_renderables
    self.render_str(
  File "/venvs/ansible-lint/lib/python3.10/site-packages/rich/console.py", line 1424, in render_str
    rich_text = render_markup(
  File "/venvs/ansible-lint/lib/python3.10/site-packages/rich/markup.py", line 168, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/]' at position 0 has nothing to close
```

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible-lint 6.8.0 using ansible 2.13.4

```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

alpine linux

**Comment by ssbarnea** [comment]
Sorry but that is not a valid bug report. You failed to mention the command executed and which data produced this error. I am sure there must be a bug, but this report makes it impossible to find.
