### ISSUE TITLE
Homebrew install of 6.9.1 fails due to mismatched Python versions

### ISSUE THREAD

**Issue by jorhett** [ansible/ansible-lint#2803]
##### Summary

Ansible lint 6.9.1 is failing in Homebrew due to using a different Python than Ansible itself

```
$ ansible-lint
Traceback (most recent call last):
  File "/opt/homebrew/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible-lint/6.9.1/libexec/lib/python3.11/site-packages/ansiblelint/__main__.py", line 347, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible-lint/6.9.1/libexec/lib/python3.11/site-packages/ansiblelint/__main__.py", line 228, in main
    from ansiblelint.rules import RulesCollection
  File "/opt/homebrew/Cellar/ansible-lint/6.9.1/libexec/lib/python3.11/site-packages/ansiblelint/rules/__init__.py", line 19, in <module>
    import ansiblelint.utils
  File "/opt/homebrew/Cellar/ansible-lint/6.9.1/libexec/lib/python3.11/site-packages/ansiblelint/utils.py", line 37, in <module>
    from ansible.errors import AnsibleError, AnsibleParserError
ModuleNotFoundError: No module named 'ansible'
```

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
$ uname -a
Darwin JoR-mbp 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64

$ ansible-lint --version
ansible-lint 6.9.1 using ansible 2.13.6
```

- ansible installation method: Homebrew
- ansible-lint installation method: Homebrew

##### STEPS TO REPRODUCE

```shell
```

```console (paste below)
$ brew install ansible ansible-lint
...
$ ansible-lint
Traceback (most recent call last):
  File "/opt/homebrew/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible-lint/6.9.1/libexec/lib/python3.11/site-packages/ansiblelint/__main__.py", line 347, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible-lint/6.9.1/libexec/lib/python3.11/site-packages/ansiblelint/__main__.py", line 228, in main
    from ansiblelint.rules import RulesCollection
  File "/opt/homebrew/Cellar/ansible-lint/6.9.1/libexec/lib/python3.11/site-packages/ansiblelint/rules/__init__.py", line 19, in <module>
    import ansiblelint.utils
  File "/opt/homebrew/Cellar/ansible-lint/6.9.1/libexec/lib/python3.11/site-packages/ansiblelint/utils.py", line 37, in <module>
    from ansible.errors import AnsibleError, AnsibleParserError
ModuleNotFoundError: No module named 'ansible'
```

##### Desired Behavior

It should work 😁 

##### Actual Behavior

```
$ ansible-lint
Traceback (most recent call last):
  File "/opt/homebrew/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible-lint/6.9.1/libexec/lib/python3.11/site-packages/ansiblelint/__main__.py", line 347, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible-lint/6.9.1/libexec/lib/python3.11/site-packages/ansiblelint/__main__.py", line 228, in main
    from ansiblelint.rules import RulesCollection
  File "/opt/homebrew/Cellar/ansible-lint/6.9.1/libexec/lib/python3.11/site-packages/ansiblelint/rules/__init__.py", line 19, in <module>
    import ansiblelint.utils
  File "/opt/homebrew/Cellar/ansible-lint/6.9.1/libexec/lib/python3.11/site-packages/ansiblelint/utils.py", line 37, in <module>
    from ansible.errors import AnsibleError, AnsibleParserError
ModuleNotFoundError: No module named 'ansible'
```

I suspect this is because ansible-lint is using Python 3.11 while ansible is still using Python 3.10:

```
$ ansible --version
ansible [core 2.13.6]
  config file = None
  configured module search path = ['/Users/jrhett/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/6.6.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/jrhett/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]
  jinja version = 3.1.2
  libyaml = True

$ brew info ansible
==> ansible: stable 6.6.0 (bottled), HEAD
Automate deployment, configuration, and upgrading
https://www.ansible.com/
/opt/homebrew/Cellar/ansible/6.6.0 (29,264 files, 369.4MB) *
  Poured from bottle on 2022-11-09 at 18:06:45
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ansible.rb
License: GPL-3.0-or-later
==> Dependencies
Build: pkg-config ✔, rust ✘
Required: openssl@1.1 ✔, python@3.11 ✔, pyyaml ✔, six ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 49,954 (30 days), 151,925 (90 days), 614,228 (365 days)
install-on-request: 49,219 (30 days), 149,941 (90 days), 606,138 (365 days)
build-error: 10 (30 days)

$ brew info ansible-lint
==> ansible-lint: stable 6.9.1 (bottled)
Checks ansible playbooks for practices and behaviour
https://github.com/ansible/ansible-lint/
/opt/homebrew/Cellar/ansible-lint/6.9.1 (1,466 files, 16.7MB) *
  Poured from bottle on 2022-12-09 at 14:12:59
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ansible-lint.rb
License: MIT and GPL-3.0-or-later
==> Dependencies
Build: pkg-config ✔
Required: ansible ✔, black ✔, pygments ✔, python@3.11 ✔, pyyaml ✔, yamllint ✔
==> Analytics
install: 7,329 (30 days), 23,479 (90 days), 58,693 (365 days)
install-on-request: 7,324 (30 days), 23,477 (90 days), 58,690 (365 days)
build-error: 0 (30 days)
```

**Comment by ssbarnea** [comment]
We support only the [installation or distribution methods mentioned in our documentation](https://ansible-lint.readthedocs.io/installing/), for anything else please contact the repackagers. Please do not raise bugs upstream for downstream issues.
