### ISSUE TITLE
include_tasks with lookup causes "TypeError: argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by richm** [ansible/ansible-lint#2875]
##### Summary

```
>ansible-lint --version
ansible-lint 6.10.2 using ansible 2.14.1
```

The following code in tasks/junk.yml:
```yaml
- name: Perform platform/version specific tasks
  include_tasks: "{{ lookup('first_found', __ff_params) }}"
  vars:
    __ff_params:
      files:
        - "{{ ansible_facts['distribution'] ~ '_' ~
              ansible_facts['distribution_version'] }}.yml"
        - "{{ ansible_facts['distribution'] ~ '_' ~
              ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
        - "default.yml"
      paths:
        - "{{ role_path }}/tasks/setup"
```
then run `ansible-lint -vv` gives the following error:
```
Traceback (most recent call last):
  File "/home/rmeggins/.ansible-lint/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/home/rmeggins/.ansible-lint/lib64/python3.10/site-packages/ansiblelint/__main__.py", line 344, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/home/rmeggins/.ansible-lint/lib64/python3.10/site-packages/ansiblelint/__main__.py", line 242, in main
    result = _get_matches(rules, options)
  File "/home/rmeggins/.ansible-lint/lib64/python3.10/site-packages/ansiblelint/runner.py", line 235, in _get_matches
    matches.extend(runner.run())
  File "/home/rmeggins/.ansible-lint/lib64/python3.10/site-packages/ansiblelint/runner.py", line 166, in run
    matches.extend(self._emit_matches(files))
  File "/home/rmeggins/.ansible-lint/lib64/python3.10/site-packages/ansiblelint/runner.py", line 204, in _emit_matches
    for child in ansiblelint.utils.find_children(lintable):
  File "/home/rmeggins/.ansible-lint/lib64/python3.10/site-packages/ansiblelint/utils.py", line 226, in find_children
    for child in play_children(basedir, item, lintable.kind, playbook_dir):
  File "/home/rmeggins/.ansible-lint/lib64/python3.10/site-packages/ansiblelint/utils.py", line 306, in play_children
    return delegate_map[k](basedir, k, v, parent_type)
  File "/home/rmeggins/.ansible-lint/lib64/python3.10/site-packages/ansiblelint/utils.py", line 318, in _include_children
    if "{{" in v:  # pragma: no branch
TypeError: argument of type 'NoneType' is not iterable
```

The problem is that the code uses `disable_lookups=True` for some reason, so the output of the template evaluation `v` is `None`.  Not sure what to do here - perhaps a special case for `_include_children` when `v` is `None`?

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version
ansible-lint 6.10.2 using ansible 2.14.1
```

- ansible installation method: one of source, pip, OS package
- ansible-lint installation method: one of source, pip, OS package

##### STEPS TO REPRODUCE

```console (paste below)

```

##### Desired Behavior

Possible security bugs should be reported via email to `security@ansible.com`

##### Actual Behavior

Please give some details of what is happening.
Include a [minimum complete verifiable example] with:

- minimized playbook to reproduce the error
- the output of running ansible-lint including the command line used
- if you're getting a stack trace, also the output of
  `ansible-playbook --syntax-check playbook`

```paste below

```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by ssbarnea** [comment]
I am unable to reproduce this with 6.12.0, so I supposed it was fixed.
