### ISSUE TITLE
Cannot import AnsibleCollectionLoader from ansible.utils.collection_loader

### ISSUE THREAD

**Issue by jvanderaa** [ansible/ansible-lint#3204]
##### Summary

When attempting to build a container that installs Ansible Lint on top of Ansible get an error:
ERROR! Unexpected Exception, this is probably a bug: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader' (/usr/local/lib/python3.9/site-packages/ansible/utils/collection_loader/__init__.py

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
FROM python:3.9
```

- ansible installation method: pip
- ansible-lint installation method:  pip

##### STEPS TO REPRODUCE

Running a `make build` to build a container that has just ansible & ansible-lint with the following Makefile and other files:

```
IMG_NAME=testing/ansible
IMG_VERSION=1.0.0

.PHONY: build
build:
	docker build -t $(IMG_NAME):$(IMG_VERSION) . 
```

Dockerfile
```console (paste below)
FROM python:3.9

COPY . /local
WORKDIR /local
RUN apt-get update && apt-get install apt-utils -y 
RUN cat requirements.system | xargs apt-get install -y

RUN pip install --no-cache -r requirements.txt
RUN ansible-galaxy collection install -r requirements.yml
CMD /bin/bash
```

requirements.txt
```console
ansible==2.9.27
ansible-lint
# bandit
# black
# paramiko
# pylint
# pytest
# pytest-pythonpath
# yamllint
```
requirements.yml
```
---
collections:
  - name: community.general
  # - name: cisco.ios
  # - name: cisco.nxos
  # - name: arista.eos

# roles:
#   - name: ansible-network.network-engine

```

##### Desired Behavior

Container image to be built.

##### Actual Behavior

```console
 > [8/8] RUN ansible-galaxy collection install -r requirements.yml:                                                                                               
#12 0.441 ERROR! Unexpected Exception, this is probably a bug: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader' (/usr/local/lib/python3.9/site-packages/ansible/utils/collection_loader/__init__.py)                                                                                             
#12 0.442 the full traceback was:                                                                                                                                 
#12 0.442 
#12 0.442 Traceback (most recent call last):
#12 0.442   File "/usr/local/bin/ansible-galaxy", line 92, in <module>
#12 0.442     mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
#12 0.442   File "/usr/local/lib/python3.9/site-packages/ansible/cli/__init__.py", line 22, in <module>
#12 0.442     from ansible.inventory.manager import InventoryManager
#12 0.442   File "/usr/local/lib/python3.9/site-packages/ansible/inventory/manager.py", line 38, in <module>
#12 0.442     from ansible.plugins.loader import inventory_loader
#12 0.442   File "/usr/local/lib/python3.9/site-packages/ansible/plugins/loader.py", line 26, in <module>
#12 0.442     from ansible.utils.collection_loader import AnsibleCollectionLoader, AnsibleFlatMapLoader, AnsibleCollectionRef
#12 0.442 ImportError: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader' (/usr/local/lib/python3.9/site-packages/ansible/utils/collection_loader/__init__.py)
```

Please give some details of what is happening.
Include a [minimum complete verifiable example] with:

- When the container image requirements.txt removes the `ansible-lint` package from PIP install the container builds without issue.
- Similar issue was seen in the Ansible-Lint GitHub action without a resolution - https://github.com/ansible/ansible-lint-action/issues/41

**Comment by ssbarnea** [comment]
We require Ansible 2.12 or newer, please do not file bugs for older verisions.
