### ISSUE TITLE
Latest ansible-lint release (v6.15.0) incompatible with latest ansible-compat (v4.0.2)

### ISSUE THREAD

**Issue by Histalek** [ansible/ansible-lint#3408]
##### Summary

Having the latest release of both ansible-lint and ansible-compat installed makes ansible-lint unusable.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansiblelint/__main__.py", line 370, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansiblelint/__main__.py", line 208, in main
    initialize_options(argv[1:])
  File "/usr/lib/python3.11/site-packages/ansiblelint/__main__.py", line 125, in initialize_options
    options.cache_dir = get_cache_dir(options.project_dir)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible_compat/prerun.py", line 13, in get_cache_dir
    basename = project_dir.resolve().name.encode(encoding="utf-8")
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'resolve'
```

- ansible installation method: OS package (Alpine edge)
- ansible-lint installation method: OS package (Alpine edge)

##### STEPS TO REPRODUCE

I'll be using podman and the alpine:edge container for this.

```console (paste below)
$ podman run -it docker.io/library/alpine:edge
/ # apk add ansible-lint
[...]
(67/86) Installing py3-ansible-compat (4.0.2-r0)
[...]
(85/86) Installing ansible-core (2.14.5-r0)
(86/86) Installing ansible-lint (6.15.0-r0)
[...]
/ # ansible-lint --version
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansiblelint/__main__.py", line 370, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansiblelint/__main__.py", line 208, in main
    initialize_options(argv[1:])
  File "/usr/lib/python3.11/site-packages/ansiblelint/__main__.py", line 125, in initialize_options
    options.cache_dir = get_cache_dir(options.project_dir)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible_compat/prerun.py", line 13, in get_cache_dir
    basename = project_dir.resolve().name.encode(encoding="utf-8")
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'resolve'
```

##### Desired Behavior

Working ansible-lint

##### Actual Behavior

see steps to reproduce

##### Notes

This is essentially the same as #3393 but that issue got closed for being about ansible-lint 6.11 .

Reading that issue makes me believe that a patch release with at least up to 2fca3fe should fix this issue.

**Comment by ssbarnea** [comment]
We released https://github.com/ansible/ansible-lint/releases/tag/v6.16.0 to address this issue. If you want to use older versions, you will need to manually pin-down ansible-compat version to avoid use of v4.
