### ISSUE TITLE
ansible-lint crashes on argv option for the command module (Ansible 2.6)

### ISSUE THREAD

**Issue by maxwell-k** [ansible/ansible-lint#352]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
$ ansible --version
ansible 2.6.1
  config file = None
  configured module search path = ['/home/chronos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.4 (default, Apr  6 2018, 05:23:32) [GCC 6.4.0]
$ ansible-lint --version
ansible-lint 3.4.23
```

- ansible installation method: OS package (Alpine Linux)
- ansible-lint installation method: pip also tested with earlier OS package

# Desired Behaviour

The following is a valid play in Ansible 2.6 so ansible-lint should parse this and show relevant warnings, for example all tasks should be named:

```
---
- name: Demonstrate ansible-lint failure
  hosts: localhost
  tasks:
  - command:
      argv:
      - echo
      - a
      - b
```

# Actual Behaviour (Bug report only)

ansible-lint output:

```
$ ansible-lint example.yaml
Traceback (most recent call last):
  File "/home/chronos/test/bin/ansible-lint", line 11, in <module>
    load_entry_point('ansible-lint==3.4.23', 'console_scripts', 'ansible-lint')()
  File "/home/chronos/test/lib/python3.6/site-packages/ansiblelint/__main__.py", line 176, in main
    matches.extend(runner.run())
  File "/home/chronos/test/lib/python3.6/site-packages/ansiblelint/__init__.py", line 243, in run
    skip_list=self.skip_list))
  File "/home/chronos/test/lib/python3.6/site-packages/ansiblelint/__init__.py", line 139, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/home/chronos/test/lib/python3.6/site-packages/ansiblelint/__init__.py", line 70, in matchtasks
    result = self.matchtask(file, task)
  File "/home/chronos/test/lib/python3.6/site-packages/ansiblelint/rules/CommandsInsteadOfArgumentsRule.py", line 54, in matchtask
    first_cmd_arg = task["action"]["__ansible_arguments__"][0]
IndexError: list index out of range
```

Playbook output:

```
$ ansible-playbook example.yaml
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'


PLAY [Demonstrate ansible-lint failure] *************************************************************************

TASK [Gathering Facts] ******************************************************************************************
ok: [localhost]

TASK [command] **************************************************************************************************
changed: [localhost]

PLAY RECAP ******************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```

**Comment by maxwell-k** [comment]
Tagging command tasks using argv as `skip_ansible-lint` is a workaround to make sure ansible-lint is running on the rest of the file

**Comment by meersjo** [comment]
Is this still brand new after 5 months? :-p Freshly installed with pip, version 3.5.1.

Same problem here. Will mark argv as skip for the time being.

**Comment by awcrosby** [comment]
Yes, was just waiting on CI :)
