### ISSUE TITLE
Invalid version when using git+ssh repo in galaxy.yml

### ISSUE THREAD

**Issue by iishabakaev** [ansible/ansible-lint#3600]
##### Summary

Cant run ansible-lint if I use git+ssh repo as dependency in galaxy.yml

```
packaging.version.InvalidVersion: Invalid version: '//git@git/pdo/kubespray.git:v2.22.1'
```

I use kubespray collection as dependency in my collection

galaxy.yml:
```
dependencies:
  "git+ssh://git@git/pdo/kubespray.git": "v2.22.1" # just a mirror for github repo in bitbucket
```

I can install my collection with using requirements.yml just fine
```
>ansible-galaxy install -r requirements.yml -vvvvv -f
Starting galaxy collection install process
Process install dependency map
Cloning into '/home/user/.ansible/tmp/ansible-local-134717a4fulq9o/tmpmz_c0_3h/kubespray8hng2s3o'
...
Installing 'ds.kubernetes:1.0.0' to '/home/user/.ansible/collections/ansible_collections/ds/kubernetes'
Created collection for dsis.kubernetes:1.0.0 at /home/user/.ansible/collections/ansible_collections/dsis/kubernetes
ds.kubernetes:1.0.0 was installed successfully
Installing 'kubernetes_sigs.kubespray:2.21.0' to '/home/user/.ansible/collections/ansible_collections/kubernetes_sigs/kubespray'
...
kubernetes_sigs.kubespray:2.21.0 was installed successfully
```

requirements.yml:
```
collections:
  - name: /home/user/ds.kubernetes/
    type: dir
```

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
>ansible-lint --version
ansible-lint 6.17.2 using ansible-core:2.15.1 ansible-compat:4.1.2 ruamel-yaml:0.17.32 ruamel-yaml-clib:0.2.7
```

```console
>ansible --version
ansible [core 2.15.1]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

Using ubuntu in WSL:
```console
>cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

- ansible installation method: pip3
- ansible-lint installation method: pip3

##### STEPS TO REPRODUCE

- Install latest ansible and ansible-lint
- Create new collection with ansible
- Set dependency git+ssh kubespray collection repo in galaxy.yml
- Run ansible-lint

##### Desired Behavior

Collection dependencies will be installed

##### Actual Behavior

```
Traceback (most recent call last):
  File "/home/u_m18t7/.local/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/home/u_m18t7/.local/lib/python3.10/site-packages/ansiblelint/__main__.py", line 317, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/home/u_m18t7/.local/lib/python3.10/site-packages/ansiblelint/__main__.py", line 255, in main
    app = get_app(offline=None)  # to be sure we use the offline value from settings
  File "/home/u_m18t7/.local/lib/python3.10/site-packages/ansiblelint/app.py", line 405, in get_app
    app.runtime.prepare_environment(
  File "/home/u_m18t7/.local/lib/python3.10/site-packages/ansible_compat/runtime.py", line 584, in prepare_environment
    self.install_collection(
  File "/home/u_m18t7/.local/lib/python3.10/site-packages/ansible_compat/runtime.py", line 417, in install_collection
    if matches and CollectionVersion(matches[1]).is_prerelease:
  File "/home/u_m18t7/.local/lib/python3.10/site-packages/ansible_compat/runtime.py", line 74, in __init__
    super().__init__(version)
  File "/home/u_m18t7/.local/lib/python3.10/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '//git@git/pdo/kubespray.git:v2.22.1'
```

**Comment by ajinkyau** [comment]
@iishabakaev the way you have mentioned the dependency is different than what is expected.
It should be something like:
```
dependencies:
  "git@github.com:my-collections/ansible.scm.git": "v1.1.0"
```

**Comment by iishabakaev** [comment]
@ajinkyau but bitbucket for ssh links use syntax like "ssh://git@bitbucket.com/kubespray.git"

With your suggestion I got an error:

```
dependencies:
  "git@git/pdo/kubespray.git": "v2.22.1"
```

```
fatal: 'git@git/pdo/kubespray.git:v2.22.1' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR! Failed to clone a Git repository from `git@git/pdo/kubespray.git:v2.22.1`.
```

For example in ansible-galaxy its valid and working syntax:

```
dependencies:
  "git+ssh://git@git/pdo/kubespray.git": "v2.22.1"
```

**Comment by ajinkyau** [comment]
@iishabakaev can you give me reproducer for this, like a public collection on bitbucket?
Need to reproduce this at my end.
