### ISSUE TITLE
offline mode still validates git versions

### ISSUE THREAD

**Issue by RobinGoussey** [ansible/ansible-lint#3673]
##### Summary
In our company, we have the following dependencies in our galaxy.yml:

dependencies:
  "git@git.company.com:automation/ansible/collections/mycollection.git": "main"
  "git@git.company:automation/ansible/collections/mycollection2.git": "main"

However, when we run ansible-lint, we get the following error:

```console
Traceback (most recent call last):
  File "/home/rgoussey/.local/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/home/rgoussey/.local/lib/python3.10/site-packages/ansiblelint/__main__.py", line 310, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/home/rgoussey/.local/lib/python3.10/site-packages/ansiblelint/__main__.py", line 258, in main
    app = get_app()
  File "/home/rgoussey/.local/lib/python3.10/site-packages/ansiblelint/app.py", line 387, in get_app
    app.runtime.prepare_environment(
  File "/home/rgoussey/.local/lib/python3.10/site-packages/ansiblelint/_vendor/ansible_compat/runtime.py", line 511, in prepare_environment
    self.install_collection(
  File "/home/rgoussey/.local/lib/python3.10/site-packages/ansiblelint/_vendor/ansible_compat/runtime.py", line 344, in install_collection
    if matches and CollectionVersion(matches[1]).is_prerelease:
  File "/home/rgoussey/.local/lib/python3.10/site-packages/ansiblelint/_vendor/ansible_compat/runtime.py", line 73, in __init__
    super().__init__(version)
  File "/home/rgoussey/.local/lib/python3.10/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'automation/ansible/collections/mycollection.git:main'

```

We however use offline mode, but this seems to have been broken in a recent version:

Broken:
ansible-lint 6.17.2 using ansible-core:2.15.3 ansible-compat:4.1.5 ruamel-yaml:0.17.32 ruamel-yaml-clib:0.2.7

Working:
ansible-lint 6.14.6 using ansible 2.15.3

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint 6.17.2 using ansible-core:2.15.3 ansible-compat:4.1.5 ruamel-yaml:0.17.32 ruamel-yaml-clib:0.2.7
```
- ansible installation method: pip
- ansible-lint installation method: one of source, pip, OS package

##### STEPS TO REPRODUCE

Create a galaxy.yml

```yml
namespace: test
name: test
version: 0.1.1
readme: README.md
authors:
  - engineering@test.com
description: A repository
license:
  - GPL-2.0-or-later
repository: ""
license_file: ""
tags: []
dependencies:
  "git@gitlab.company.com:automation/ansible/collections/mycollection.git": "main"
```
Run
```console (paste below)
ansible-lint
```

##### Desired Behavior

I feel like offline mode shouldn't verify the version?

##### Actual Behavior

Error above

**Comment by ssbarnea** [comment]
@RobinGoussey I have reasons to believe that the example you gave does not work with `ansible-galaxy collection install .`.

I made a fix for ansible-compat that should prevent getting an exception but at the same time, I am not sure if we will do anything in particular for offline mode. We assume that any presence of git URLs in dependencies do not count as "online" dependencies, at least for now.

With current change something like below will work:
```
dependencies:
  git+https://github.com/ansible-collections/ansible.posix.git: main
```
