### ISSUE TITLE
lfops: Lint Auto fix mode results in traceback KeyError for invalid playbook

### ISSUE THREAD

**Issue by justjais** [ansible/ansible-lint#3848]
##### Summary
Lint Auto fix mode results in traceback KeyError for invalid playbook

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT
macos

```console (paste below)
ansible-lint --version
```
version: 6.20.3

##### STEPS TO REPRODUCE

Run ansible-lint via command: `ansible-lint --format md --config-file ./ansible-lint.yml`, over repo: https://github.com/Linuxfabrik/lfops, will result in below traceback.

```
Traceback (most recent call last):
  File "/Users/sjaiswal/Sumit/wisdom/ansible-wisdom-service/.env/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sjaiswal/Sumit/wisdom/ansible-wisdom-service/.env/lib/python3.11/site-packages/ansiblelint/__main__.py", line 376, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/Users/sjaiswal/Sumit/wisdom/ansible-wisdom-service/.env/lib/python3.11/site-packages/ansiblelint/__main__.py", line 353, in main
    fix(runtime_options=options, result=result, rules=rules)
  File "/Users/sjaiswal/Sumit/wisdom/ansible-wisdom-service/.env/lib/python3.11/site-packages/ansiblelint/__main__.py", line 238, in fix
    _do_transform(result, options)
  File "/Users/sjaiswal/Sumit/wisdom/ansible-wisdom-service/.env/lib/python3.11/site-packages/ansiblelint/__main__.py", line 193, in _do_transform
    transformer.run()
  File "/Users/sjaiswal/Sumit/wisdom/ansible-wisdom-service/.env/lib/python3.11/site-packages/ansiblelint/transformer.py", line 110, in run
    self._do_transforms(file, ruamel_data or data, file_is_yaml, matches)
  File "/Users/sjaiswal/Sumit/wisdom/ansible-wisdom-service/.env/lib/python3.11/site-packages/ansiblelint/transformer.py", line 147, in _do_transforms
    match.rule.transform(match, file, data)
  File "/Users/sjaiswal/Sumit/wisdom/ansible-wisdom-service/.env/lib/python3.11/site-packages/ansiblelint/rules/key_order.py", line 111, in transform
    task[key] = task.pop(key)
                ^^^^^^^^^^^^^
  File "/Users/sjaiswal/Sumit/wisdom/ansible-wisdom-service/.env/lib/python3.11/site-packages/ruamel/yaml/comments.py", line 915, in pop
    result = self[key]
             ~~~~^^^^^
  File "/Users/sjaiswal/Sumit/wisdom/ansible-wisdom-service/.env/lib/python3.11/site-packages/ruamel/yaml/comments.py", line 842, in __getitem__
    return ordereddict.__getitem__(self, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tags'
```

Ansible lint yml:
```ansible-lint.yml
---
exclude_paths:
  - .github/
  - .git/
  - .vscode/
  - .devcontainer/
  - changelogs/
  - .cache/
  - .pre-commit-config.yaml


write_list:
  - all
```

##### Desired Behavior
Ansible lint runs over the repo and suggests the fix without failing and resulting into traceback

##### Actual Behavior
Ansible lint runs over the repo, and fails with the traceback

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by ajinkyau** [comment]
Fixed in 6.21.0
