### ISSUE TITLE
Multiple "Ignored exception"s when using command: true

### ISSUE THREAD

**Issue by dennisse** [ansible/ansible-lint#3995]
##### Summary
When using `true` as a command, I get the following errors:
```
WARNING  Ignored exception from CommandsInsteadOfModulesRule.<bound method AnsibleLintRule.matchtasks of command-instead-of-module: Using command rather than module.> while processing play-test.yaml (playbook): can only join an iterable
WARNING  Ignored exception from EnvVarsInCommandRule.<bound method AnsibleLintRule.matchtasks of inline-env-var: Command module does not accept setting environment variables inline.> while processing play-test.yaml (playbook): can only join an iterable
```

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

macOS 14.2.1

```console (paste below)
$ ansible-lint --version
ansible-lint 6.22.2 using ansible-core:2.16.1 ansible-compat:4.1.11 ruamel-yaml:0.18.5 ruamel-yaml-clib:0.2.8
```

- ansible installation method: brew
- ansible-lint installation method: brew

##### STEPS TO REPRODUCE

Playbook:
```yaml
---
- name: test
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Do the true thing
      ansible.builtin.command:
        cmd: true
      changed_when: false
```

Run:
```console
$ ansible-lint play-test.yaml
WARNING  Ignored exception from CommandsInsteadOfModulesRule.<bound method AnsibleLintRule.matchtasks of command-instead-of-module: Using command rather than module.> while processing play-test.yaml (playbook): can only join an iterable
WARNING  Ignored exception from EnvVarsInCommandRule.<bound method AnsibleLintRule.matchtasks of inline-env-var: Command module does not accept setting environment variables inline.> while processing play-test.yaml (playbook): can only join an iterable

Passed: 0 failure(s), 0 warning(s) on 1 files. Last profile that met the validation criteria was 'production'.

$ ansible-playbook --syntax-check play-test.yaml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

playbook: play-test.yaml
```
The syntax-check was performed in a directory with just `play-test.yaml`, which causes those warnings. When run in a normal ansible-folder, no warnings are thrown.

##### Desired Behavior

No exceptions are thrown

##### Actual Behavior

Two exceptions are thrown (though ignored).

<details>
<summary><b>Verbose output</b></summary>

```console
$ ansible-lint play-test.yaml -vvv
DEBUG    Logging initialized to level 10
INFO     Identified /Users/test/git/ansible as project root due .git directory.
DEBUG    Options: Options(_skip_ansible_syntax_check=False, cache_dir=PosixPath('/Users/test/.cache/ansible-compat/0cb87f'), colored=True, configured=True, cwd=PosixPath('/Users/test/git/ansible/test'), display_relative_path=True, exclude_paths=['.cache', '.git', '.hg', '.svn', '.tox'], f
ormat=None, lintables=['play-test.yaml'], list_rules=False, list_tags=False, write_list=[], parseable=False, quiet=0, rulesdirs=[PosixPath('/opt/homebrew/Cellar/ansible-lint/6.22.2/libexec/lib/python3.12/site-packages/ansiblelint/rules')], skip_list=[], tags=[], verbosity=3, warn_list=['experimental'
, 'jinja', 'fqcn'], mock_filters=[], mock_modules=[], mock_roles=[], loop_var_prefix=None, only_builtins_allow_collections=[], only_builtins_allow_modules=[], var_naming_pattern=None, offline=None, project_dir='/Users/test/git/ansible', extra_vars=None, enable_list=[], skip_action_validatio
n=True, strict=False, rules={}, profile=None, task_name_prefix='{stem} | ', sarif_file=None, config_file=None, generate_ignore=False, rulesdir=[], use_default_rules=False, version=False, list_profiles=False, ignore_file=None, max_tasks=100, max_block_depth=20, nodeps=False)
DEBUG    CWD: /Users/test/git/ansible/test
DEBUG    Logging initialized to level 10
INFO     Set ANSIBLE_LIBRARY=/Users/test/.cache/ansible-compat/9f86d0/modules:/Users/test/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/Users/test/.cache/ansible-compat/9f86d0/collections:/Users/test/.ansible/collections:/usr/share/ansible/collections:/opt/homebrew/opt/ansible/libexec/lib/python3.12/site-packages
INFO     Set ANSIBLE_ROLES_PATH=/Users/test/.cache/ansible-compat/9f86d0/roles:/Users/test/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
DEBUG    Loading custom /Users/test/.config/yamllint/config config file, this extends our internal yamllint config.
DEBUG    Effective yamllint rules used: {'anchors': {'level': 'error', 'forbid-undeclared-aliases': True, 'forbid-duplicated-anchors': False, 'forbid-unused-anchors': False}, 'braces': {'level': 'error', 'forbid': False, 'min-spaces-inside': 0, 'max-spaces-inside': 0, 'min-spaces-inside-empty': -1, '
max-spaces-inside-empty': -1}, 'brackets': {'level': 'error', 'forbid': False, 'min-spaces-inside': 0, 'max-spaces-inside': 0, 'min-spaces-inside-empty': -1, 'max-spaces-inside-empty': -1}, 'colons': {'level': 'error', 'max-spaces-before': 0, 'max-spaces-after': 1}, 'commas': {'level': 'error', 'max-
spaces-before': 0, 'min-spaces-after': 1, 'max-spaces-after': 1}, 'comments': {'level': 'warning', 'require-starting-space': True, 'ignore-shebangs': True, 'min-spaces-from-content': 1}, 'comments-indentation': {'level': 'warning'}, 'document-end': False, 'document-start': {'level': 'warning', 'prese
nt': True}, 'empty-lines': {'level': 'error', 'max': 2, 'max-start': 0, 'max-end': 0}, 'empty-values': False, 'float-values': False, 'hyphens': {'level': 'error', 'max-spaces-after': 1}, 'indentation': {'level': 'error', 'spaces': 'consistent', 'indent-sequences': True, 'check-multi-line-strings': Fa
lse}, 'key-duplicates': {'level': 'error'}, 'key-ordering': False, 'line-length': False, 'new-line-at-end-of-file': {'level': 'error'}, 'new-lines': {'level': 'error', 'type': 'unix'}, 'octal-values': False, 'quoted-strings': False, 'trailing-spaces': {'level': 'error'}, 'truthy': {'level': 'warning'
, 'allowed-values': ['true', 'false'], 'check-keys': True}}
DEBUG    Logging initialized to level 10INFO     Set ANSIBLE_LIBRARY=/Users/test/.cache/ansible-compat/9f86d0/modules:/Users/test/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/Users/test/.cache/ansible-compat/9f86d0/collections:/Users/test/.ansible/collections:/usr/share/ansible/collections:/opt/homebrew/opt/ansible/libexec/lib/python3.12/site-packages
INFO     Set ANSIBLE_ROLES_PATH=/Users/test/.cache/ansible-compat/9f86d0/roles:/Users/test/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
INFO     Executing syntax check on playbook play-test.yaml (0.66s)
DEBUG    Examining play-test.yaml of type playbook
DEBUG    Running rule internal-error
DEBUG    Running rule load-failure
DEBUG    Running rule parser-error
DEBUG    Running rule warningDEBUG    Running rule yamlDEBUG    Running rule argsDEBUG    Running rule avoid-implicitDEBUG    Running rule command-instead-of-moduleWARNING  Ignored exception from CommandsInsteadOfModulesRule.<bound method AnsibleLintRule.matchtasks of command-instead-of-module: Using command rather than module.> while processing play-test.yaml (playbook): can only join an iterableDEBUG    Ignored exception details
Traceback (most recent call last):  File "/opt/homebrew/Cellar/ansible-lint/6.22.2/libexec/lib/python3.12/site-packages/ansiblelint/_internal/rules.py", line 93, in getmatches    matches.extend(method(file))
                   ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible-lint/6.22.2/libexec/lib/python3.12/site-packages/ansiblelint/rules/__init__.py", line 177, in matchtasks
    result = self.matchtask(task, file=file)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/homebrew/Cellar/ansible-lint/6.22.2/libexec/lib/python3.12/site-packages/ansiblelint/rules/command_instead_of_module.py", line 92, in matchtask
    first_cmd_arg = get_first_cmd_arg(task)                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible-lint/6.22.2/libexec/lib/python3.12/site-packages/ansiblelint/utils.py", line 940, in get_first_cmd_arg
    first_cmd_arg = get_cmd_args(task).split()[0]
                    ^^^^^^^^^^^^^^^^^^  File "/opt/homebrew/Cellar/ansible-lint/6.22.2/libexec/lib/python3.12/site-packages/ansiblelint/utils.py", line 933, in get_cmd_args
    return " ".join(args)           ^^^^^^^^^^^^^^TypeError: can only join an iterableDEBUG    Running rule command-instead-of-shellDEBUG    Running rule complexityDEBUG    Running rule deprecated-bare-varsDEBUG    Running rule deprecated-local-actionDEBUG    Running rule deprecated-moduleDEBUG    Running rule fqcnDEBUG    Running rule galaxyDEBUG    Running rule ignore-errors
DEBUG    Running rule inline-env-var
WARNING  Ignored exception from EnvVarsInCommandRule.<bound method AnsibleLintRule.matchtasks of inline-env-var: Command module does not accept setting environment variables inline.> while processing play-test.yaml (playbook): can only join an iterable
DEBUG    Ignored exception details
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/ansible-lint/6.22.2/libexec/lib/python3.12/site-packages/ansiblelint/_internal/rules.py", line 93, in getmatches
    matches.extend(method(file))
                   ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible-lint/6.22.2/libexec/lib/python3.12/site-packages/ansiblelint/rules/__init__.py", line 177, in matchtasks
    result = self.matchtask(task, file=file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible-lint/6.22.2/libexec/lib/python3.12/site-packages/ansiblelint/rules/inline_env_var.py", line 68, in matchtask
    first_cmd_arg = get_first_cmd_arg(task)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible-lint/6.22.2/libexec/lib/python3.12/site-packages/ansiblelint/utils.py", line 940, in get_first_cmd_arg
    first_cmd_arg = get_cmd_args(task).split()[0]
                    ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible-lint/6.22.2/libexec/lib/python3.12/site-packages/ansiblelint/utils.py", line 933, in get_cmd_args
    return " ".join(args)
           ^^^^^^^^^^^^^^
TypeError: can only join an iterable
DEBUG    Running rule jinja
DEBUG    Running rule key-order
DEBUG    Running rule latest
DEBUG    Running rule literal-compare
DEBUG    Running rule loop-var-prefix
DEBUG    Running rule meta-incorrect
DEBUG    Running rule meta-no-tags
DEBUG    Running rule meta-runtime
DEBUG    Running rule meta-video-links
DEBUG    Running rule name
DEBUG    Running rule no-changed-when
DEBUG    Running rule no-free-form
DEBUG    Running rule no-handler
DEBUG    Running rule no-jinja-when
DEBUG    Running rule no-relative-paths
DEBUG    Running rule no-tabs
DEBUG    Running rule package-latest
DEBUG    Running rule partial-become
DEBUG    Running rule playbook-extension
DEBUG    Running rule risky-file-permissions
DEBUG    Running rule risky-octal
DEBUG    Running rule risky-shell-pipe
DEBUG    Running rule role-name
DEBUG    Running rule run-once
DEBUG    Running rule sanity
DEBUG    Running rule schema
DEBUG    Running rule var-naming

DEBUG    Determined rule-profile order: {'internal-error': (0, 'min'), 'load-failure': (1, 'min'), 'parser-error': (2, 'min'), 'syntax-check': (3, 'min'), 'command-instead-of-module': (4, 'basic'), 'command-instead-of-shell': (5, 'basic'), 'deprecated-bare-vars': (6, 'basic'), 'deprecated-local-action': (7, 'basic'), 'deprecated-module': (8, 'basic'), 'inline-env-var': (9, 'basic'), 'key-order': (10, 'basic'), 'literal-compare': (11, 'basic'), 'jinja': (12, 'basic'), 'no-free-form': (13, 'basic'), 'no-jinja-when': (14, 'basic'), 'no-tabs': (15, 'basic'), 'partial-become': (16, 'basic'), 'playbook-extension': (17, 'basic'), 'role-name': (18, 'basic'), 'schema': (19, 'basic'), 'name': (20, 'basic'), 'var-naming': (21, 'basic'), 'yaml': (22, 'basic'), 'name': (23, 'moderate'), 'name': (24, 'moderate'), 'name': (25, 'moderate'), 'spell-var-name': (26, 'moderate'), 'avoid-implicit': (27, 'safety'), 'latest': (28, 'safety'), 'package-latest': (29, 'safety'), 'risky-file-permissions': (30, 'safety'), 'risky-octal': (31, 'safety'), 'risky-shell-pipe': (32, 'safety'), 'galaxy': (33, 'shared'), 'ignore-errors': (34, 'shared'), 'layout': (35, 'shared'), 'meta-incorrect': (36, 'shared'), 'meta-no-tags': (37, 'shared'), 'meta-video-links': (38, 'shared'), 'meta-version': (39, 'shared'), 'meta-runtime': (40, 'shared'), 'no-changed-when': (41, 'shared'), 'no-changelog': (42, 'shared'), 'no-handler': (43, 'shared'), 'no-relative-paths': (44, 'shared'), 'max-block-depth': (45, 'shared'), 'max-tasks': (46, 'shared'), 'unsafe-loop': (47, 'shared'), 'avoid-dot-notation': (48, 'production'), 'sanity': (49, 'production'), 'fqcn': (50, 'production'), 'import-task-no-when': (51, 'production'), 'meta-no-dependencies': (52, 'production'), 'single-entry-point': (53, 'production'), 'use-loop': (54, 'production')}
Passed: 0 failure(s), 0 warning(s) on 1 files. Last profile that met the validation criteria was 'production'.

$ ansible-playbook --syntax-check play-test.yaml -vvv
ansible-playbook [core 2.16.1]
  config file = None
  configured module search path = ['/Users/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/9.1.0/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/test/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible-playbook
  python version = 3.12.1 (main, Dec  7 2023, 20:45:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/opt/homebrew/Cellar/ansible/9.1.0/libexec/bin/python)
  jinja version = 3.1.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
1 plays in play-test.yaml

playbook: play-test.yaml
```

</details>

**Comment by ajinkyau** [comment]
@dennisse `cmd` accepts a `string` instead of a `boolean`.
For more info refer https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html#parameters
