### ISSUE TITLE
KeyError when fixing playbook containing multiple blocks with wrong key order

### ISSUE THREAD

**Issue by zack-mayoh** [ansible/ansible-lint#4091]
##### Summary

`ansible-lint --fix` breaks with a `KeyError` in the `key-order` rule when run on a yaml file containing multiple blocks where blocks after the first have incorrect key order.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint 6.22.2 using ansible-core:2.15.10 ansible-compat:4.1.11 ruamel-yaml:None ruamel-yaml-clib:None
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

Run `ansible-lint --fix` on the following test playbook:
```yaml
---
- name: Test multiple blocks with when in wrong order
  hosts: all
  tasks:
    - name: First block
      when: true
      block:
        - name: Test1
          ansible.builtin.debug:
            msg: Foo

- name: Second play
  hosts: all
  tasks:
    - name: Second block
      block:
        - name: Test2
          ansible.builtin.debug:
            msg: Baz
      when: true
```

##### Desired Behavior

Should fix the key order of the incorrect block without breaking.

##### Actual Behavior

Results of `ansible-lint --fix`:
```console
$ ansible-lint --fix test.yml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/usr/local/lib/python3.9/site-packages/ansiblelint/__main__.py", line 402, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python3.9/site-packages/ansiblelint/__main__.py", line 379, in main
    fix(runtime_options=options, result=result, rules=rules)
  File "/usr/local/lib/python3.9/site-packages/ansiblelint/__main__.py", line 248, in fix
    _do_transform(result, options)
  File "/usr/local/lib/python3.9/site-packages/ansiblelint/__main__.py", line 203, in _do_transform
    transformer.run()
  File "/usr/local/lib/python3.9/site-packages/ansiblelint/transformer.py", line 118, in run
    self._do_transforms(file, ruamel_data or data, file_is_yaml, matches)
  File "/usr/local/lib/python3.9/site-packages/ansiblelint/transformer.py", line 156, in _do_transforms
    match.rule.transform(match, file, data)
  File "/usr/local/lib/python3.9/site-packages/ansiblelint/rules/key_order.py", line 139, in transform
    task[key] = task.pop(key)
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/comments.py", line 926, in pop
    result = self[key]
  File "/usr/local/lib/python3.9/site-packages/ruamel/yaml/comments.py", line 853, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'when'
```

Results of `ansible-playbook --syntax-check playbook`:
```console
$ ansible-playbook -i localhost, --syntax-check test.yml

playbook: test.yml
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by kitos9112** [comment]
Just faced the same issue but with a `notify` keyword. 

```
Traceback (most recent call last):
  File "/home/me/projects/ansible/provisioning/main/extension/setup/../../../../opt/tf-ansible-WA5-pL_2-py3.11/bin/ansible-lint", line 10, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/projects/ansible/opt/tf-ansible-WA5-pL_2-py3.11/lib/python3.11/site-packages/ansiblelint/__main__.py", line 400, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/home/me/projects/ansible/opt/tf-ansible-WA5-pL_2-py3.11/lib/python3.11/site-packages/ansiblelint/__main__.py", line 377, in main
    fix(runtime_options=options, result=result, rules=rules)
  File "/home/me/projects/ansible/opt/tf-ansible-WA5-pL_2-py3.11/lib/python3.11/site-packages/ansiblelint/__main__.py", line 246, in fix
    _do_transform(result, options)
  File "/home/me/projects/ansible/opt/tf-ansible-WA5-pL_2-py3.11/lib/python3.11/site-packages/ansiblelint/__main__.py", line 207, in _do_transform
    transformer.run()
  File "/home/me/projects/ansible/opt/tf-ansible-WA5-pL_2-py3.11/lib/python3.11/site-packages/ansiblelint/transformer.py", line 113, in run
    self._do_transforms(file, ruamel_data or data, file_is_yaml, matches)
  File "/home/me/projects/ansible/opt/tf-ansible-WA5-pL_2-py3.11/lib/python3.11/site-packages/ansiblelint/transformer.py", line 151, in _do_transforms
    match.rule.transform(match, file, data)
  File "/home/me/projects/ansible/opt/tf-ansible-WA5-pL_2-py3.11/lib/python3.11/site-packages/ansiblelint/rules/name.py", line 195, in transform
    isinstance(task["notify"], str)
               ~~~~^^^^^^^^^^
  File "/home/me/projects/ansible/opt/tf-ansible-WA5-pL_2-py3.11/lib/python3.11/site-packages/ruamel/yaml/comments.py", line 853, in __getitem__
    return ordereddict.__getitem__(self, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'notify'
```

**Comment by Qalthos** [comment]
> Just faced the same issue but with a `notify` keyword.

That's actually https://github.com/ansible/ansible-lint/issues/4093 instead, but thanks for the report

**Comment by Qalthos** [comment]
That really _is_ the most minimal reproducer. Amazing.

What's going on here as best as I can figure is that the rule is getting confused, but only with a block in a second play. Anything less than that... two tasks in one play, only the second play has a block, plays in a different order, _anything_ else, and the rule correctly identifies the location of the error. But with this _specific_ organization of plays and tasks, the rule points to the task inside the block and not the block itself as the culprit, which does not in fact have a `when` keyword.

This hopefully shouldn't be too hard to fix, at least not once I've figured out _why_ it's doing that.

**Comment by TamiTakamiya** [comment]
jFYI. Though I think it is the same error that was already fixed by #4116, I saw the `KeyError: 'notify'` when I ran ansible-lint (24.2.2) with --fix option against playbooks under:

https://github.com/ansible-collections/amazon.aws/tree/main/tests/integration/targets/inventory_aws_rds/playbooks
and
https://github.com/ansible-collections/amazon.aws/tree/main/tests/integration/targets/inventory_aws_ec2/playbooks

**Comment by TamiTakamiya** [comment]
After applying the #4116 change to the local ansible-lint, I no longer saw the error even when running `ansible-lint --fix` against the whole [amazon.aws repo](https://github.com/ansible-collections/amazon.aws.git).

**Comment by TamiTakamiya** [comment]
Sorry I have sent a few comments, which should have been added to #4093.  Comments were deleted.
