### ISSUE TITLE
ansible-lint --fix name crashes with KeyError: 'notify' on isinstance(task["notify"], str)

### ISSUE THREAD

**Issue by RayJin2000** [ansible/ansible-lint#4093]
##### Summary
ansible-lint --fix name crashes with KeyError: 'notify' on isinstance(task["notify"], str)

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version
ansible-lint 24.2.1 using ansible-core:2.16.5 ansible-compat:4.1.11 ruamel-yaml:0.18.6 ruamel-yaml-clib:0.2.7
```

##### STEPS TO REPRODUCE

```yaml
---
- name: test
  hosts: localhost

  tasks:
    - name: test
      ansible.builtin.debug:
        msg: test
```

```console (paste below)
 > ansible-lint test.yml --fix name
Traceback (most recent call last):
  File "/home/user/.local/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/ansiblelint/__main__.py", line 400, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/ansiblelint/__main__.py", line 377, in main
    fix(runtime_options=options, result=result, rules=rules)
  File "/home/user/.local/lib/python3.12/site-packages/ansiblelint/__main__.py", line 246, in fix
    _do_transform(result, options)
  File "/home/user/.local/lib/python3.12/site-packages/ansiblelint/__main__.py", line 207, in _do_transform
    transformer.run()
  File "/home/user/.local/lib/python3.12/site-packages/ansiblelint/transformer.py", line 113, in run
    self._do_transforms(file, ruamel_data or data, file_is_yaml, matches)
  File "/home/user/.local/lib/python3.12/site-packages/ansiblelint/transformer.py", line 151, in _do_transforms
    match.rule.transform(match, file, data)
  File "/home/user/.local/lib/python3.12/site-packages/ansiblelint/rules/name.py", line 195, in transform
    isinstance(task["notify"], str)
               ~~~~^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/ruamel/yaml/comments.py", line 853, in __getitem__
    return ordereddict.__getitem__(self, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'notify'

```

##### Desired Behavior

a hint that the task name should be uppercase.

```nushell
 > ansible-lint test.yml --fix yaml
WARNING  Listing 2 violation(s) that are fatal
name[casing]: All names should start with an uppercase letter.
test.yml:2

name[casing]: All names should start with an uppercase letter.
test.yml:6 Task/Handler: test

Read documentation for instructions on how to ignore specific rule violations.

              Rule Violation Summary              
 count tag          profile  rule associated tags 
     2 name[casing] moderate idiom                

Failed: 2 failure(s), 0 warning(s) on 1 files. Last profile that met the validation criteria was 'basic'. Rating: 1/5 star

```

**Comment by TamiTakamiya** [comment]
jFYI. I saw this issue when I ran `ansible-lint --fix` against ansible files in [amazon.aws repo](https://github.com/ansible-collections/amazon.aws.git). With applying #4091 fix to the local ansible-lint, those errors disappeared.
