### ISSUE TITLE
Broken version 6.17.2-1 on Ubuntu 24.04

### ISSUE THREAD

**Issue by gioclaxit** [ansible/ansible-lint#4138]
##### Summary

Default installation on Ubuntu 24.04 seems broken with error on python dependecy module 'pathlib'

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

`Ubuntu 24.04`

```
ansible [core 2.16.3]
  config file = None
  configured module search path = ['******/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = *******/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```
`ansible-lint 6.17.2-1`

```console (paste below)
ansible-lint --version
```
All packages installed via apt with default repo

##### STEPS TO REPRODUCE

`ansible-lint --version`

```console (paste below)
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 5, in <module>
    from ansiblelint.__main__ import _run_cli_entrypoint
  File "/usr/lib/python3/dist-packages/ansiblelint/__main__.py", line 39, in <module>
    from ansiblelint import cli
  File "/usr/lib/python3/dist-packages/ansiblelint/cli.py", line 20, in <module>
    from ansiblelint.file_utils import (
  File "/usr/lib/python3/dist-packages/ansiblelint/file_utils.py", line 15, in <module>
    import wcmatch.pathlib
  File "/usr/lib/python3/dist-packages/wcmatch/pathlib.py", line 218, in <module>
    class PurePosixPath(PurePath):
  File "/usr/lib/python3/dist-packages/wcmatch/pathlib.py", line 221, in PurePosixPath
    _flavour = pathlib._posix_flavour  # type: ignore[attr-defined]
               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pathlib' has no attribute '_posix_flavour'

```

##### Desired Behavior

No errors

##### Actual Behavior

Error

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by ssbarnea** [comment]
@gioclaxit Clearly you did not reach the first line of the form: 

> 
Verify first that your issue is not already reported on GitHub 

Duplicate: #4123

**Comment by ssbarnea** [comment]
Please follow-up on https://bugs.launchpad.net/ubuntu/+source/python-wcmatch/+bug/2060649
