### ISSUE TITLE
Failure to check Booleans in conditionals

### ISSUE THREAD

**Issue by ggwena** [ansible/ansible-lint#445]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible 2.4.3.0
ansible-lint 4.0.0
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

Return syntax is OK

# Actual Behaviour

I get a Traceback with  `TypeError: argument of type 'bool' is not iterable`: 
```
Traceback (most recent call last):
  File ".../bin/ansible-lint", line 11, in <module>
    sys.exit(main())
  File ".../local/lib/python2.7/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File ".../local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 243, in run
    skip_list=self.skip_list))
  File ".../local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 139, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File ".../local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 70, in matchtasks
    result = self.matchtask(file, task)
  File ".../local/lib/python2.7/site-packages/ansiblelint/rules/UseHandlerRatherThanWhenChangedRule.py", line 47, in matchtask
    if _changed_in_when(item):
  File ".../local/lib/python2.7/site-packages/ansiblelint/rules/UseHandlerRatherThanWhenChangedRule.py", line 28, in _changed_in_when
    ['.changed', '|changed', '["changed"]', "['changed']"])
  File ".../local/lib/python2.7/site-packages/ansiblelint/rules/UseHandlerRatherThanWhenChangedRule.py", line 27, in <genexpr>
    return any(changed in item for changed in
TypeError: argument of type 'bool' is not iterable
```

Here's that example code:
```
- name: Test ansible-lint bug with conditionals
  hosts: localhost
  tasks:
    - name: Dont execute this step
      debug:
        msg: "this should not be printed"
      when:
        - false
```

(I know the case is pretty weird...)

`ansible-playbook --syntax-check` does not return any error.

**Comment by ggwena** [comment]
also tested with ansible==2.7.5
