### ISSUE TITLE
`ansible-lint` 24.12.2 doesn't start 

### ISSUE THREAD

**Issue by iwane-pl** [ansible/ansible-lint#4453]
##### Summary

`ansible-lint` doesn't start. It seems like `ansible-compat.prerun.get_cache_dir` expects a `Path`, while lint's `options` provides a path in string form.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
$ ansible-lint --version
Traceback (most recent call last):
  File "/repo/ansible/.venv/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/repo/ansible/.venv/lib/python3.12/site-packages/ansiblelint/__main__.py", line 319, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/repo/ansible/.venv/lib/python3.12/site-packages/ansiblelint/__main__.py", line 181, in main
    initialize_options(argv[1:])
  File "/repo/ansible/.venv/lib/python3.12/site-packages/ansiblelint/__main__.py", line 104, in initialize_options
    options.cache_dir = get_cache_dir(options.project_dir)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/repo/ansible/.venv/lib/python3.12/site-packages/ansible_compat/prerun.py", line 14, in get_cache_dir
    basename = project_dir.resolve().name.encode(encoding="utf-8")
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'resolve'

```

```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
(...)
```

- ansible installation method: `pip` (more precisely: `uv`)
- ansible-lint installation method: `pip` (more precisely: `uv`)

##### STEPS TO REPRODUCE

```
$ ansible-lint
Traceback (most recent call last):
  File "/repo/ansible/.venv/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/repo/ansible/.venv/lib/python3.12/site-packages/ansiblelint/__main__.py", line 319, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/repo/ansible/.venv/lib/python3.12/site-packages/ansiblelint/__main__.py", line 181, in main
    initialize_options(argv[1:])
  File "/repo/ansible/.venv/lib/python3.12/site-packages/ansiblelint/__main__.py", line 104, in initialize_options
    options.cache_dir = get_cache_dir(options.project_dir)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/repo/ansible/.venv/lib/python3.12/site-packages/ansible_compat/prerun.py", line 14, in get_cache_dir
    basename = project_dir.resolve().name.encode(encoding="utf-8")
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'resolve'

```

##### Desired Behavior
Runs.

##### Actual Behavior
Doesn't run at all...

**Comment by iwane-pl** [comment]
Sorry. PEBKAC. `uv` installed wrong `ansible-lint` release.
