### ISSUE TITLE
Empty task "-" crashes ansible-lint

### ISSUE THREAD

**Issue by qinqon** [ansible/ansible-lint#468]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible --version
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ellorent/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ellorent/.local/lib/python2.7/site-packages/ansible
  executable location = /home/ellorent/.local/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:24:06) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]

ansible-lint --version
ansible-lint 3.4.23
```

- ansible installation method: one of source, pip, OS package
  pip install --user ansible
- ansible-lint installation method: one of source, pip, OS package
  pre-commit call with git commit -a --amend

# Desired Behaviour

If you have a list of tasks with an empty want if have to report you as failure
- name: foobar
  debug:
    msg: Hello world
- 

# Actual Behaviour (Bug report only)

Instead of failing with a proper message it crashes
Traceback (most recent call last):
  File "/home/ellorent/.cache/pre-commit/repoHkh3h8/py_env-python2/bin/ansible-lint", line 11, in <module>
    sys.exit(main())
  File "/home/ellorent/.cache/pre-commit/repoHkh3h8/py_env-python2/lib/python2.7/site-packages/ansiblelint/__main__.py", line 176, in main
    matches.extend(runner.run())
  File "/home/ellorent/.cache/pre-commit/repoHkh3h8/py_env-python2/lib/python2.7/site-packages/ansiblelint/__init__.py", line 229, in run
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/home/ellorent/.cache/pre-commit/repoHkh3h8/py_env-python2/lib/python2.7/site-packages/ansiblelint/utils.py", line 169, in find_children
    items = _playbook_items(playbook_ds)
  File "/home/ellorent/.cache/pre-commit/repoHkh3h8/py_env-python2/lib/python2.7/site-packages/ansiblelint/utils.py", line 154, in _playbook_items
    return [item for play in pb_data for item in play.items()]
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by awcrosby** [comment]
We can make a change to prevent ansible-lint from crashing on an empty task (`ansible` and `yamllint` don’t throw an error on this example)

I’m not sure how useful it would be, but we could have a line-based rule to check for a line equal to `-`

**Comment by besmirzanaj** [comment]
facing this error and the verbosity is useless. At least pinpoint which file has the error and if possible which task line

**Comment by angelos-se** [comment]
This is very desirable function.

I'm trying to check my playbook using ansible-lint now, but I'm hit with this error on first run. Any tips on quickly locating the offending role / tasks?
