### ISSUE TITLE
Crash with AttributeError

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible/ansible-lint#509]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
$ ansible --version
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
$ ansible-lint --version
ansible-lint 4.1.0+dfsg.1
```

- ansible installation method: OS package (from Ansible repo)
- ansible-lint installation method: OS package (from Debian backports, due to lack of official repo)

# Desired Behaviour
Lint my playbooks.

# Actual Behaviour
When trying to lint any playbook (for example the one I added, which is just toy-around playbook), I receive AttributeErrors from ansible-lint. Even when the playbook itself works fine and gives no errors.

Did I miss something? :-)

- playbook
```
---
- hosts: localhost
  gather_facts: no
  tasks:
    - pause:
        prompt: "Is this OK?"
      register: var

    - debug:
        msg: "{{ var.user_input }}"

    - pause:
        prompt: "Stuff?"
      when: var.user_input == "yes"
      register: cond_var

    - debug:
        msg: "Stuff is {{ cond_var.user_input }}"
      when: cond_var.user_input is defined
```
- output of running ansible-lint
```
$ ansible-lint input.yml 
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 11, in <module>
    load_entry_point('ansible-lint==4.1.0+dfsg.1', 'console_scripts', 'ansible-lint')()
  File "/usr/lib/python2.7/dist-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/usr/lib/python2.7/dist-packages/ansiblelint/__init__.py", line 282, in run
    skip_list=self.skip_list))
  File "/usr/lib/python2.7/dist-packages/ansiblelint/__init__.py", line 174, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/usr/lib/python2.7/dist-packages/ansiblelint/__init__.py", line 84, in matchtasks
    yaml = ansiblelint.utils.append_skipped_rules(yaml, text, file['type'])
  File "/usr/lib/python2.7/dist-packages/ansiblelint/utils.py", line 603, in append_skipped_rules
    yaml = ruamel.yaml.YAML()
AttributeError: 'module' object has no attribute 'YAML'
```
-   output `ansible-playbook --syntax-check playbook`
```
$ ansible-playbook --syntax-check input.yml 

playbook: input.yml
```

**Comment by awcrosby** [comment]
I was able to recreate by using an older version of ruamel.yaml, so if you update that pip package it should resolve this.

We will update the dependencies to require a minimal version for this.

**Comment by Thulium-Drake** [comment]
Cool, just curious, which version of ruamel.yaml is required to make it work? I'll log a bug against the backports package (as Debian only features ruamel.yaml 0.13.4-2)
