### ISSUE TITLE
Error with ruamel.yaml version 0.16.0

### ISSUE THREAD

**Issue by jfx** [ansible/ansible-lint#556]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```console
$ ansible --version
ansible 2.8.1
  config file = None
  configured module search path = ['/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May  3 2019, 11:24:39) [GCC 8.3.0]

$ ansible-lint --version
ansible-lint 4.1.0
```

- ansible installation method: pip
- ansible-lint installation method: pip
# Desired Behaviour

Fix ruamel.yaml dependency lower than 0.16.0

# Actual Behaviour (Bug report only)

ruamel.yaml 0.16.0 was recently published and with this version
```python-traceback
ansible-lint playbook.yml
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/usr/lib/python3.7/site-packages/ansiblelint/__init__.py", line 282, in run
    skip_list=self.skip_list))
  File "/usr/lib/python3.7/site-packages/ansiblelint/__init__.py", line 175, in run
    matches.extend(rule.matchyaml(playbookfile, text))
  File "/usr/lib/python3.7/site-packages/ansiblelint/__init__.py", line 116, in matchyaml
    yaml = ansiblelint.utils.append_skipped_rules(yaml, text, file['type'])
  File "/usr/lib/python3.7/site-packages/ansiblelint/utils.py", line 603, in append_skipped_rules
    yaml = ruamel.yaml.YAML()
AttributeError: module 'ruamel.yaml' has no attribute 'YAML'
```
The same command with an installation of ruamel.yaml version 0.15.100 before installation of ansible and ansible-lint works fine.

**Comment by atrutko-4xxi** [comment]
++++
This error blocks my CI checks [GitLab-CI screenshot](https://i.imgur.com/khGpq57.png)

```
$ ansible --version
ansible 2.8.3
  config file = None
  configured module search path = ['/ansible/library']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May  3 2019, 11:24:39) [GCC 8.3.0]

$ pip install ansible-lint
Requirement already satisfied: ansible-lint in /usr/lib/python3.7/site-packages (4.1.0)
Requirement already satisfied: six in /usr/lib/python3.7/site-packages (from ansible-lint) (1.12.0)
Requirement already satisfied: ruamel.yaml in /usr/lib/python3.7/site-packages (from ansible-lint) (0.16.0)
Requirement already satisfied: pyyaml in /usr/lib/python3.7/site-packages (from ansible-lint) (5.1.1)
Requirement already satisfied: ansible in /usr/lib/python3.7/site-packages (from ansible-lint) (2.8.3)
Requirement already satisfied: ruamel.yaml.clib; platform_python_implementation == "CPython" and python_version < "3.8" in /usr/lib/python3.7/site-packages (from ruamel.yaml->ansible-lint) (0.1.0)
Requirement already satisfied: jinja2 in /usr/lib/python3.7/site-packages (from ansible->ansible-lint) (2.10.1)
Requirement already satisfied: cryptography in /usr/lib/python3.7/site-packages (from ansible->ansible-lint) (2.7)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3.7/site-packages (from jinja2->ansible->ansible-lint) (1.1.1)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python3.7/site-packages (from cryptography->ansible->ansible-lint) (0.24.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/lib/python3.7/site-packages (from cryptography->ansible->ansible-lint) (1.12.3)
Requirement already satisfied: pycparser in /usr/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography->ansible->ansible-lint) (2.19)

$ find ./ -type f -name "*.yml" ! -name ".*" -exec ansible-lint {} +
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/usr/lib/python3.7/site-packages/ansiblelint/__init__.py", line 282, in run
    skip_list=self.skip_list))
  File "/usr/lib/python3.7/site-packages/ansiblelint/__init__.py", line 174, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/usr/lib/python3.7/site-packages/ansiblelint/__init__.py", line 84, in matchtasks
    yaml = ansiblelint.utils.append_skipped_rules(yaml, text, file['type'])
  File "/usr/lib/python3.7/site-packages/ansiblelint/utils.py", line 603, in append_skipped_rules
    yaml = ruamel.yaml.YAML()
AttributeError: module 'ruamel.yaml' has no attribute 'YAML'
```

**Comment by madeinoz67** [comment]
from package info <https://pypi.org/project/ruamel.yaml/> 

> Starting with version 0.15.0 the way YAML files are loaded and dumped is changing. See the API doc for details. Currently existing functionality will throw a warning before being changed/removed. For production systems you should pin the version being used with ``ruamel.yaml<=0.15``

**Comment by wilmardo** [comment]
See this issue over at Bitbucket:
https://bitbucket.org/ruamel/yaml/issues/299/importerror-cannot-import-name-yaml-from

**Comment by Hendrik44** [comment]
This error is related to ansible lint version 4.1.0. If you reinstall 4.0.1 all is working fine.

Tested with ansible 2.8.3 in a alpine docker image. This error also broke my ci-molecule setup

**Comment by ca-johnson** [comment]
> Try setting ruamel.yaml < 0.16.0 in the requirements.txt

This worked for us. Thanks.

**Comment by wilmardo** [comment]
This should be resolved:
https://bitbucket.org/ruamel/yaml/issues/299/importerror-cannot-import-name-yaml-from

**Comment by webknjaz** [comment]
Closing as per above.
