### ISSUE TITLE
Crash when trying to lint an invalid file 

### ISSUE THREAD

**Issue by wedi** [ansible/ansible-lint#651]
When globbing a role directory with a readme file like this `ansible-lint roles/*`, `ansible-lint` crashes on the readme (or any other plain file):

```bash
ansible-lint roles/*        
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/ansible-lint/4.2.0/libexec/lib/python3.7/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/usr/local/Cellar/ansible-lint/4.2.0/libexec/lib/python3.7/site-packages/ansiblelint/__init__.py", line 267, in run
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/usr/local/Cellar/ansible-lint/4.2.0/libexec/lib/python3.7/site-packages/ansiblelint/utils.py", line 161, in find_children
    items = _playbook_items(playbook_ds)
  File "/usr/local/Cellar/ansible-lint/4.2.0/libexec/lib/python3.7/site-packages/ansiblelint/utils.py", line 146, in _playbook_items
    return [item for play in pb_data for item in play.items()]
  File "/usr/local/Cellar/ansible-lint/4.2.0/libexec/lib/python3.7/site-packages/ansiblelint/utils.py", line 146, in <listcomp>
    return [item for play in pb_data for item in play.items()]
AttributeError: 'str' object has no attribute 'items'
```

# Ansible and Ansible Lint details

```
$ ansible --version
ansible 2.9.2
$ ansible-lint --version
ansible-lint 4.2.0
```

- ansible installation method: OS package (homebrew)
- ansible-lint installation method: OS package (homebrew)

# Desired Behaviour

Of course this can be avoided by better globbing ~or excluding files~ but `ansible-lint` should not fatally crash when hitting an invalid file.

# Actual Behaviour (Bug report only)

Ugly error message. See above.

**Edit:** `ansible-lint roles/*` cashes even when adding `'./roles/README.md'` to the `exclude_paths` in `.ansible_lint`.

**Comment by ssbarnea** [comment]
Not a bug, that works as garbage-in, garbage-out. You should be aware of the fact that shell does the expansion of * and the linter is called with the README.md.
