### ISSUE TITLE
[HELP WANTED] [SEND PR] Missing Git breaks the auto-discovery of YAML files

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible-lint#735]
FTR here's the traceback from that log:
```python-traceback
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/__main__.py", line 153, in main
    args = get_playbooks_and_roles(options=options)
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/utils.py", line 772, in get_playbooks_and_roles
    files = OrderedDict.fromkeys(sorted(subprocess.check_output(
  File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

_Originally posted by @webknjaz in https://github.com/ansible/ansible-lint-action/pull/26#issuecomment-614621653_

**Comment by webknjaz** [comment]
@anryko I think the fix is to add `FileNotFoundError` here: https://github.com/ansible/ansible-lint/pull/650/files#diff-8a54e9ace4c09bec09fd356284e1853eR783.

**Comment by webknjaz** [comment]
P.S. This also requires a regression test.

**Comment by anryko** [comment]
@webknjaz You are right, done.
