### ISSUE TITLE
Empty roles key crashes ansible-lint

### ISSUE THREAD

**Issue by maxwell-k** [ansible/ansible-lint#798]
##### Summary

If a play includes an empty roles key then `ansible-lint` crashes. 

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console
$ ansible --version
ansible 2.9.9
  config file = /media/removable/GOLD/configuration/ansible.cfg
  configured module search path = ['/home/chronos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 15 2020, 01:53:50) [GCC 9.3.0]
$ ansible-lint --version
ansible-lint 4.2.0
```

- ansible installation method: OS package
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

Reproducible on localhost on Alpine Linux.

##### STEPS TO REPRODUCE
With the following as `example.yaml`:

```yaml
- name: Example play
  hosts: all
  roles:
  tasks:
    - name: Debug message
      debug: { msg: hello world }
```

`ansible-lint` crashes:

```python-traceback
$ ansible-lint example.yaml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 10, in <module>
    sys.exit(main())
  File "/opt/ansible-lint/lib/python3.8/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/opt/ansible-lint/lib/python3.8/site-packages/ansiblelint/__init__.py", line 286, in run
    matches.extend(self.rules.run(file, tags=set(self.tags),
  File "/opt/ansible-lint/lib/python3.8/site-packages/ansiblelint/__init__.py", line 178, in run
    matches.extend(rule.matchyaml(playbookfile, text))
  File "/opt/ansible-lint/lib/python3.8/site-packages/ansiblelint/__init__.py", line 125, in matchyaml
    result = self.matchplay(file, play)
  File "/opt/ansible-lint/lib/python3.8/site-packages/ansiblelint/rules/NoFormattingInWhenRule.py", line 27, in matchplay
    for role in play['roles']:
TypeError: 'NoneType' object is not iterable
```

##### Desired Behaviour

I expected `ansible-lint` to complete execution.

##### Actual Behaviour

```python-traceback
$ ansible-lint -vvv example.yaml
Examining example.yaml of type playbook
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 10, in <module>
    sys.exit(main())
  File "/opt/ansible-lint/lib/python3.8/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/opt/ansible-lint/lib/python3.8/site-packages/ansiblelint/__init__.py", line 286, in run
    matches.extend(self.rules.run(file, tags=set(self.tags),
  File "/opt/ansible-lint/lib/python3.8/site-packages/ansiblelint/__init__.py", line 178, in run
    matches.extend(rule.matchyaml(playbookfile, text))
  File "/opt/ansible-lint/lib/python3.8/site-packages/ansiblelint/__init__.py", line 125, in matchyaml
    result = self.matchplay(file, play)
  File "/opt/ansible-lint/lib/python3.8/site-packages/ansiblelint/rules/NoFormattingInWhenRule.py", line 27, in matchplay
    for role in play['roles']:
TypeError: 'NoneType' object is not iterable
```

```yaml
$ ansible-playbook --syntax-check example.yaml

playbook: example.yaml
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by ssbarnea** [comment]
Have you tried with latest pre-release or master branch?

**Comment by webknjaz** [comment]
This looks fixed in master: https://github.com/ansible/ansible-lint/blob/eca19dd/lib/ansiblelint/rules/NoFormattingInWhenRule.py#L20-L21
