### ISSUE TITLE
Ansible lint should not crash with an empty config file

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#813]
##### Summary
```
ansible-lint -c /dev/null
```

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
Traceback (most recent call last):
File "/Users/ssbarnea/.pyenv/versions/3.8.2/bin/ansible-lint", line 11, in <module>
load_entry_point('ansible-lint', 'console_scripts', 'ansible-lint')()
File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/__main__.py", line 45, in main
options = cli.get_config(sys.argv[1:])
File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/cli.py", line 204, in get_config
config = load_config(options.config_file)
File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/cli.py", line 78, in load_config
expand_to_normalized_paths(config, config_dir)
File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/cli.py", line 41, in expand_to_normalized_paths
if paths_var not in config:
TypeError: argument of type 'NoneType' is not iterable
```

Desired behavior: run the same way as if no config would exist, avoiding a crash.

**Comment by ssbarnea** [comment]
@webknjaz FYI, if user mentions an invalid filename, the tool will end with an error, like below:
```
$ ansible-lint -c /dev/sdsds -v                                                                                                                     Config file not found '/dev/sdsds'
FAIL: 2
```

This change only allows running with empty existing config files, which are still valid YAML files. Basically /dev/null was used just as an example.
